networks:
  binquant_network:
    driver: bridge

services:
  binquant:
    build: ./binquant
    image: binquant
    container_name: binquant
    restart: always
    networks:
      - binquant_network
    env_file:
      - .env
    environment:
      - BACKEND_DOMAIN=https://api.terminal.binbot.in
      - FRONTEND_DOMAIN=https://terminal.binbot.in
      - ENV=production
    command: ["python3", "main.py"]
