name: PR checks
on: pull_request
env:
  ACTIONS_RUNNER_DEBUG: true
  SECRET_KEY: test
  ENV: ci
  FLASK_DOMAIN: https://api.terminal.binbot.in/
  FRONTEND_DOMAIN: https://terminal.binbot.in/
  PYARROW_IGNORE_TIMEZONE: "1"

jobs:
  deploy_binquant:
    name: Test and deploy binquant
    runs-on: ubuntu-latest
    env:
      IMAGE: binquant:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build image
        run: docker build --tag $IMAGE .
      - name: Test container starts
        run: docker run --name binquant -d $IMAGE
      - name: Tag images
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker commit $IMAGE carloswufei/$IMAGE &
          docker tag $IMAGE carloswufei/$IMAGE
      - name: Push to Docker Hub
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push carloswufei/$IMAGE

  python-tests:
    name: 🐍 Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          python -m pip install uv --upgrade pip
          uv venv && source .venv/bin/activate
          uv sync --all-extras --dev
          uv run pytest .

  python-linting:
    name: Python code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./.python-version"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run linters
        run: |
          uv run ruff check .
          uv run mypy .
